{% set version = "2022.07.0" %}

package:
  name: uxarray
  version: {{ version }}

source:
  url: https://github.com/UXARRAY/uxarray/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: a889a376a3785f853a588c418f2c5378e081a134e13a358c84cb11551ccab3f0

build:
  number: 2

  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - xarray

test:
  source_files:
    - test
  requires:
    - dask
    - netcdf4
    - pytest
    - numba
    - numpy >=1.2, <1.22
    - scipy >=0.16
    - xarray
  imports:
    - uxarray
  commands:
    - conda info
    - conda list
    - python -m pytest

about:
  home: https://github.com/UXARRAY/uxarray
  description: |
    Uxarray aims to address the geoscience community need for tools that enable standard data analysis techniques to operate directly on unstructured grid data. 
    Uxarray will provide Xarray styled functions to better read in and use unstructured grid datasets that follow standard conventions, including UGRID, SCRIP, 
    Exodus and shapefile formats. This effort is a result of the collaboration between Project Raijin 
    (NCAR and Pennsylvania State University) and the SEATS Project (Argonne National Laboratory, UC Davis, and Lawrence Livermore National Laboratory). 
    The Uxarray team welcomes other community members to become part of this collaboration at any level of contribution.
    
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Uxarray is a library of xarray based functions for visualizing unstructured grid datasets'

extra:
  recipe-maintainers:
    - paullric
    - erogluorhan
    - anissa111
    - michaelavs
    - rajeeja
    - chengzhuzhang
    - marodrig
